mysite/myapp/urls.py
"""
This documentation describes the URL configuration for a Django application named ShopApp.
The configuration handles URL routing, linking URLs to specific views,
and is designed for an e-commerce or shopping application context
"""


from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import groups_list, shop_index, create_order, ProductsListView, \
    ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView, OrderDetailView, OrderUpdateView, \
    HelloView, \
    ProductViewSet, OrdersListView, ProductsDataExportView

app_name = 'myapp'


router = DefaultRouter()
router.register('products',ProductViewSet)


urlpatterns = [
    path('hello/', HelloView.as_view(), name='hello'),
    path('api/',include(router.urls)),
    path("", shop_index, name='shop_index'),
    path('groups/', groups_list,name='groups_list'),
    path('orders/', create_order, name='create-order'),
    path('order/',OrdersListView.as_view(),name='order-list'),
    path('products/',ProductsListView.as_view(), name='products-list'),
    path('create/',ProductCreateView.as_view(), name='create-product'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/',ProductDetailView.as_view(), name='product_details'),
    path('products/<int:pk>/update/',ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/archived/', ProductDeleteView.as_view(), name='delete_product'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='orders_details'),
    path('order/<int:pk>/update/', OrderUpdateView.as_view(), name='update_orders'),
    ]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views  import SpectacularAPIView,SpectacularSwaggerView,SpectacularRedocView
import debug_toolbar



urlpatterns = [
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('shop/',include('myapp.urls')),
    path('admin/', admin.site.urls),
    path('',include('myapiapp.urls')),
    path('blog/',include('blogapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),



]

urlpatterns += i18n_patterns(
    path('accounts/',include('accounts.urls')),

)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
         static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )


    urlpatterns.append(
            path('__debug__/', include(debug_toolbar.urls)),
        )

mysite/myapp/models.py
"""
Module: myapp.models
This module defines the database models for the shop application.
"""

from django.contrib.auth.models import User
from django.db import models

def product_preview_directory_path(instance: 'Product', filename: str) -> str:
    return 'Uploads/product_{pk}/preview/{filename}'.format(
       pk=instance.pk,
       filename=filename
    )

class Product(models.Model):
    class Meta:
        ordering = ['-name', 'price']

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    is_archived = models.BooleanField(default=False)
    color = models.CharField(max_length=100, default="")
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self):
        return f'Product(name: {self.name}, pk={self.pk})'

class Order(models.Model):
    delivery_address = models.CharField(max_length=100)
    promocode = models.CharField(max_length=8)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    created_at = models.DateTimeField(auto_now_add=True)
    color = models.CharField(max_length=100, default="")

mysite/myapp/forms.py
"""
This module defines two forms, OrderForm and ProductForm,
which are used to collect data about orders and products, respectively.
Both forms inherit from Django's ModelForm, making it efficient to create a form directly from a model.
"""


from django import forms
from .models import Product, Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address','promocode','color'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price","description","color","preview","discount"

mysite/myapp/views.py
"""
This Python module defines various views and components for a Django web application,
centered around managing products and orders.
It leverages Django’s class-based views and REST framework capabilities for efficient development
"""

import logging
from timeit import default_timer
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group, User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, request, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, View, UpdateView, DeleteView, DetailView, CreateView
from django.utils.translation import gettext_lazy as _, ngettext
from .models import Product, Order
from .forms import OrderForm, ProductForm
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from myapiapp.serializer import ProductSerializer
from drf_spectacular.utils import extend_schema, OpenApiResponse


logger = logging.getLogger(__name__)



class ProductViewSet(ModelViewSet):

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description",]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",

    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response, product by id not found'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


def shop_index(request: HttpRequest) -> HttpResponse:
    # return HttpResponse('<h1>Hello Shop Index</1>')

    context ={
        'runtime': default_timer()
    }

    return render(request, 'myapp/index.html', context=context)


def groups_list(request: HttpRequest) -> HttpResponse:
    context = {
        'groups': Group.objects.all()
    }
    return render(request, 'myapp/groups-list.html', context=context)



class ProductDetailView(View):
    def get(self,request:HttpRequest,pk: int) -> HttpResponse:
        # product = Product.objects.get(pk=pk)
        product = get_object_or_404(Product,pk=pk)
        context = {
            'product': product,
        }
        return render(request, 'myapp/products_details.html', context=context)


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ["myapp.view_order",]
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )


class ProductUpdateView(LoginRequiredMixin,UpdateView):
    model = Product
    fields = 'name','description','price','discount',"preview"
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return reverse(
            'myapp:product_details',
            kwargs={'pk': self.object.pk},
        )


class OrderUpdateView(LoginRequiredMixin,UpdateView):
    model = Order
    form_class = OrderForm
    template_name_suffix = '_update_'

    def get_success_url(self):
        return reverse(
            'myapp:orders_details',
            kwargs={'pk': self.object.pk},
        )


class ProductDeleteView(LoginRequiredMixin,DeleteView):
    model = Product
    success_url = reverse_lazy('myapp:products-list')

    def form_valid(self,form):
        success_url = self.get_success_url()
        self.object.archived =True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductsListView(ListView):
    template_name = 'myapp/product-list.html'
    model = Product
    context_object_name = 'products'


class OrdersListView(LoginRequiredMixin,ListView):
    template_name = 'myapp/order-list.html'
    model = Order
    context_object_name = 'order'



class ProductCreateView(LoginRequiredMixin, CreateView):
    def test_func(self):
        # return self.request.user.groups.filter(name='secret-group').exists()
        return self.request.user.is_superuser

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    # form_class = ProductForm
    success_url = reverse_lazy("myapp:products-list")


def create_order(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            # form.instance.user = request.user.id
            # form.save()
            user_instance = User.objects.get(id=1)

            delivery_address = form.cleaned_data['delivery_address']
            promocode = form.cleaned_data['promocode']
            color = form.cleaned_data['color']
            order_instance = Order.objects.create(delivery_address=delivery_address, promocode=promocode, color=color , user =user_instance )
    else:
        form = OrderForm()

    context = {
        'form': form
    }

    return render(request, 'myapp/create-order.html', context=context)


class HelloView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:

        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"

        )

class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "is_archived": product.is_archived,
            }
            for product in products
        ]
        elem = products_data[0]
        name = elem['name']
        print(name)
        return JsonResponse({"products": products_data})

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
         Base
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    <h1> Base </h1>
     {% endblock %}
</body>
    <div>
       <h4>Time:{% now 'H:i:s' %}</h4>
       {% now 'l' as current_weekday %}
       {% now 'm' as current_month %}
       {% now 'Y' as current_year %}
       {% now 'd' as current_day%}
       <h4>  Today is   {{current_day}}/{{current_month}}/{{current_year}}:{{current_weekday}}:</h4>
   </div>
        <div>
    <a href="{% url 'myapp:products-list' %}"
    >Go  to products list</a>
    </div>
<div>
    <a href="{% url 'myapp:order-list' %}"
    > Go to Orders list</a>
    </div>

</html>

mysite/myapp/templates/myapp/create-order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create order</title>
</head>
<body>
  <h1>Create Order</h1>
 <h1>Create a new order</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
    </form>
    </div>
<div>
    <a href="{% url 'myapp:order-list' %}"
    >Orders list</a>
    </div>
 <div>
    <a href="{% url 'myapp:create-order' %}"
    >Create Order</a>
    </div>

</body>
</html>

mysite/myapp/templates/myapp/create-product.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Create product</title>

</head>
<body>

 <h1>Create a new product</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input class=" input--submitButton" type="submit" value="Create">


    </form>
    </div>

    <div>
    <a href="{% url 'myapp:products-list' %}"
    >Back to products list</a>
    </div>

</body>
</html>

mysite/myapp/templates/myapp/groups-list.html
{% extends 'myapp/base.html' %}

{% block title %}
   Groups
{% endblock %}

{% block body %}
<h1> Groups:</h1>
<div>
    <ul>
    {% for group in groups %}
      {{ group }}
     <ul>
      {% for permission in group.permissions.all %}
      <li>
        {{ permission.name }} (<code>{{permission.codename}}</code>)

      </li>
    {% endfor %}
     </ul>
  {% endfor %}
    </ul>
</div>
{% endblock %}ml>

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block title %}
 Shop index
{% endblock %}

{% block body %}
    <h1> Hello Shop Index</h1>
    <div>
       {% lorem 3 p random %}
    </div>
{% endblock %}

mysite/myapp/templates/myapp/order-list.html
{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <div>
        {% for order in order %}
            <div>
                 <p><a href="{% url 'myapp:orders_details' pk=order.pk %}"
                >delivery_address: {{ order.delivery_address }}</a></p>
                <p>Promocode: {{ order.promocode }}</p>
                <p>Color: {{ order.color }}</p>


            </div>


        {% endfor %}
<div>
    <a href="{% url 'myapp:create-order' %}"
    >Create Order</a>
    </div>
        <div>
    <a href="{% url 'myapp:products-list' %}"
    >Go  to products list</a>
    </div>
{% endblock %}

mysite/myapp/templates/myapp/order_detail.html
{% block title%}
  Order #{{object.pk}}
{% endblock %}

{% block body %}
<h1> <strong>Order  Name</strong> </h1>
       <div>
           <div>Delivery address:{{ object.delivery_address }}</div>
                <div>Promocode: {{ object.promocode }}</div>
                <div>Color:{{ object.color }}</div>
       </div>
<div>
    <a href="{% url 'myapp:order-list' %}"
    >Orders list</a>
    </div>
<div>
        <a href="{% url 'myapp:update_orders' pk=object.pk %}">Update order</a>
    </div>

{% endblock %}

mysite/myapp/templates/myapp/order_update_.html
{% block title %}
  Update Order
{% endblock %}

{% block body %}
  <h1> Update Order</h1>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
</div>

<div>
    <a href="{% url 'myapp:orders_details' pk=object.pk %}">Back to Order #{{ object.pk }}</a>
</div>
{% endblock %}

mysite/myapp/templates/myapp/product-list.html
{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{%block body%}
  <h1>
        {% translate 'Products' %}
  </h1>
    {% if products %}
        <div>
            {% blocktranslate count products_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ products_count }} products.
            {% endblocktranslate %}
        </div>
    {%endif%}

    <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'myapp:product_details' pk=product.pk %}"
                >{% translate 'Name'%} :{{ product.name }}</a></p>
                <h4><p>{% translate 'Description'%} : {{product.description}} </p></h4>

                <h4><p>{% translate 'Price'%} : {{ product.price }}$</p></h4>
                <h4><p>{% translate 'Discount'%} : {% firstof product.discount 'no discount' %}%</p></h4>
                <h4><p>{% translate 'Color'%} :{{ product.color }}</p></h4>

                {% if product.preview %}
                        <img src="{{product.preview.url}}" alt="{{product.preview.name}}" width="500" height="300">
                {% endif %}


            </div>
        {% endfor %}
    </div>

    <div>
    <a href="{% url 'myapp:create-product' %}"
    >Create a new product
    </a>
      <div>
    <a href="{% url 'myapp:create-order' %}"
    >Create Order</a>
    </div>
        <div>
    <a href="{% url 'myapp:order-list' %}"
    > Go to Orders list</a>
    </div>

    </div>
{%endblock%}

mysite/myapp/templates/myapp/product_confirm_delete.html
{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'myapp:product_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/myapp/templates/myapp/product_form.html
{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'myapp:products-list' %}">Back to products</a>
    </div>
{% endblock %}

mysite/myapp/templates/myapp/product_update_form.html
{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1> Update product</h1>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
</div>
<div>
    <a href="{% url 'myapp:product_details' pk=object.pk %}">Back tp product #{{ object.pk }}</a>
</div>
{% endblock %}

mysite/myapp/templates/myapp/products_details.html
{% block title %}
   Product #{{product.pk}}
{% endblock %}

{% block body %}
   <h1> Product <strong>{{ product.name }}</strong></h1>
   <div>
       <div> Description: <em>{{ product.description}}</em></div>
       <div>Price: {{ product.price }} $</div>
       <div>Discount: {{product.discount }}%</div>
       <div>Archived: {{product.is_archived}}</div>

        {% if product.preview %}
                        <img src="{{product.preview.url}}" alt="{{product.preview.name}}" width="500" height="300">
                {% endif %}
   </div>
  <div>
      <a href="{% url 'myapp:products-list' %}">Back to products </a>
  </div>
 <div>
        <a href="{% url 'myapp:update_product' pk=product.pk %}">Update product</a>
    </div>
 <div>
        <a href="{% url 'myapp:delete_product' pk=product.pk %}">Archive product</a>
    </div>
{% endblock %}